driver:
  name: vagrant

provisioner:
  name: chef_zero

verifier:
  name: inspec

platforms:
  - name: centos-6.8
  - name: centos-7.3
  - name: debian-7.11
  - name: debian-8.6
  - name: ubuntu-14.04
  - name: ubuntu-16.04
  #
  # The following (private) boxes are shared via Atlas. Please note this
  # requires adding your Atlas account to the `Chef` org and will
  # require a `vagrant login`.
  #
  # The Mac OS X boxes are VMware only also. Windows boxes support VMWare
  # and VirtualBox only.
  #
  - name: windows-2012r2
    driver:
      box: chef/windows-server-2012r2-standard # private

suites:
  - name: default
    run_list: recipe[test::default]
    excludes: windows-2012r2
  - name: one_oh
    run_list: recipe[test::default]
    attributes:
      push_jobs:
        package_version: 1.3.4
    excludes: windows-2012r2
  - name: windows
    run_list: recipe[push-jobs]
    includes: windows-2012r2
  - name: resource
    run_list: recipe[test::instance]
    excludes: windows-2012r2
