---
driver_plugin: vagrant
driver_config:
  require_chef_omnibus: 'latest'
provisioner: chef_zero
platforms:
- name: ubuntu-12.04
- name: ubuntu-10.04
- name: centos-6.4
- name: centos-5.9
suites:
- name: default
  run_list:
  - recipe[push-jobs]
  attributes:
    push_jobs:
      whitelist: {chef-client: "chef-client"}
