---
driver:
  name: proxy
  host: localhost
  reset_command: "exit 0"
  port: 5985
  username: <%= ENV["machine_user"] %>
  password: <%= ENV["machine_pass"] %>

provisioner:
  name: chef_zero
  deprecations_as_errors: true

platforms:
  - name: windows-2012R2

verifier:
  name: pester

suites:
  - name: default
    run_list:
      - recipe[push-jobs]
    attributes:
      push_jobs:
        package_version: 2.4.5
        package_url: https://packages.chef.io/files/stable/push-jobs-client/2.4.5/windows/2012/push-jobs-client-2.4.5-1-x64.msi
        package_checksum: b586ac7ed6a421cf0a81b2ac8e900441c6836b69f1b6ccee87aa40fb24486b19
