---
driver:
  name: proxy
  host: localhost
  reset_command: "exit 0"
  port: 5985
  username: <%= ENV["machine_user"] %>
  password: <%= ENV["machine_pass"] %>

provisioner:
  name: chef_zero
  deprecations_as_errors: true
  require_chef_omnibus: 12.19.36

platforms:
  - name: windows-2012R2

verifier:
  name: pester

suites:
  - name: default
    run_list:
      - recipe[push-jobs]
    attributes:
      push_jobs:
        package_version: 2.2.0
